### ISSUE TITLE
Milestone v1.0

### ISSUE THREAD

**Issue by Yukaii** [puraku/client#6]
本專案有兩大目的：

1. 學習 Vue.js
2. 填以前挖的坑

一直以來 macOS 都沒有一個足夠好用的 Plurk App，用慣了 macOS 下優質 App 的我想當然爾應當貢獻一下。雖然截止目前並不是一個十分活躍的噗浪使用者，希望做完之後除了變腦粉外，也能順便推廣 Plurk。附帶一題，最終的 App 會是全平臺的，順便連 Windows App 都給他上架一下 😈 

目前專案在做完「Basic Layout #4 」和「Basic API Usage #5 」之後，整體的樣貌就慢慢可以想像了。因為 Plurk API 實在有些歷史，近年來的改動也不多，API 的部分只要隨著 UI 的演進慢慢擴增即可 🎉 

為了完成 v1.0，會有以下要做的任務： 

### 📓 架構、套件 

- [ ] 導入 vuex
- [ ] 導入 vue-router
- [ ] Plurks poling 實作
- [ ] Notification

### 🎁  UI

- [ ] 個人頁面
- [ ] Plurk show 頁面
- [ ] 回覆 Plurk 界面
- [ ] 發文界面，希望是獨立 Pop out
- [ ] 設定頁面
- [ ] Public Plurks Streaming

### 📜  雜項

- [ ] 完成過場動畫
- [ ] App theming，噗浪令人最喜愛的地方就是能用 css 自訂個人頁面，如果 App 也能達成就太好了。

**Comment by Yukaii** [comment]
![screen shot 2016-10-28 at 5 17 27 pm](https://cloud.githubusercontent.com/assets/4230968/19801610/7a9f85ee-9d32-11e6-9606-092ea616d311.png)

**Comment by Yukaii** [comment]
目前的設計主要是~~抄襲~~參考：

1. macOS 版的 twitter App
2. iOS 版的 Plurk App

當然素材那些也只能先用免費的，比如 fontawesome，之後再來研究看看第三方 Plurk App 一般是怎麽弄。我真的很不想自己拉 icon 呀 XDDD

**Comment by Yukaii** [comment]
會選用 Vue 絕對不是因為 GitLb 的這一篇：[Why We Chose Vue.js](https://about.gitlab.com/2016/10/20/why-we-chose-vue/)，我也是今天看報者才知道。目前寫起來是還沒到綁手綁腳啦，只是做一個 App 魔鬼藏在細節裡，加上又沒有 deadline 很容易永無止境開新坑啊 😆

**Comment by Yukaii** [comment]
### Create plurk todos

- [ ] privacy => selection group ui ?
- [ ] emoicons
- [ ] Image upload

上一個 PR 有提到 https://github.com/puraku/client/pull/18#issuecomment-257909742

> 編輯介面有大坑啊，網頁版的 Plurk 是用 textarea 弄的，App 端當然不能僅僅這樣實作 w，一定要有個inline 的貼圖插入才行，不過上傳圖片、emoji 等等又得多花些時間處裡，等於是實作一個小的 WYSIWYG 編輯器惹 😅 
> 
> * https://code.tutsplus.com/tutorials/create-a-wysiwyg-editor-with-the-contenteditable-attribute--cms-25657

之後再開坑處裡

**Comment by Yukaii** [comment]
差不多可以開始重構了 😓  最大單一 component 長到 300 行

**Comment by Yukaii** [comment]
呀，最近事情一多這邊感覺這邊進度也不會走太快了，好險有前兩週的衝刺 XDD

**Comment by Yukaii** [comment]
靠腰，什麼叫**還算活躍的開發**啦！已經一個月沒更新了 Q__Q

**Comment by Yukaii** [comment]
# 狀態說明

2016 年底的 puraku 至今也快兩歲半了，老實說，~~自從在臉書 F2E 發宣傳文騙星星之後，這個專案就沒有 commit 了~~ （幹

兩年半在前端世界裡來說可說人間十年，Vue 快出 4 了，webpack 也朝 5 邁進，puraku 開起來噴一堆 warnings 和 errors，Plurk API 可能也有小改版吧，~~整個專案重寫說不定還比較快~~；想要體驗升級 legacy code 的話倒是個很棒的經驗 (X)

### Possible Short-term Roadmap

1. 修正錯誤 (6 weeks)
	- 整理開發文件 (1st week)
	- 開 console 玩過現有的功能，把所有的 warning 和 error 開成 issue (1st week)
	- 基本的 linter + CI/CD 架構建立 (1st week)
	- 一週兩張票的速度把最 critical 的票解完 (3~5 weeks)
2. 升級套件與重構 (4 weeks)
	- 升級 webpack
	- 升級 Vue
	- 升級 Vuex
	- Review 各式套件
	- 整理 Vuex Store 形狀，與各種 action
	- 全面採用最新 es 語法
3. 長期維護和新功能 (TBD)

假如只有這個 Side Project 就能用這種速度做完吧 😆 很可惜並不是，所以時間乘二或三會更合理點。
